# Generated by Django 4.2.6 on 2024-07-03 13:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('provider', 'Provider'), ('user', 'User')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Quản lý người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tendichvu', models.CharField(max_length=200, null=True)),
                ('mota_dichvu', models.TextField(blank=True, null=True)),
                ('gia_dichvu', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Quản lý dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tenhuyen', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quản lý quận huyện',
            },
        ),
        migrations.CreateModel(
            name='KhachSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tenkhachsan', models.CharField(max_length=200, null=True)),
                ('diachi', models.CharField(max_length=200, null=True)),
                ('sdt', models.CharField(max_length=11, null=True)),
                ('mota', models.CharField(max_length=200, null=True)),
                ('email_ks', models.CharField(max_length=200, null=True)),
                ('dichvu', models.ManyToManyField(blank=True, to='app.dichvu')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quản lý khách sạn',
            },
        ),
        migrations.CreateModel(
            name='Payment_VNPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('order_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TienNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/%Y/%m')),
                ('tentiennghi', models.CharField(max_length=200, null=True)),
                ('mota_tiennghi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quản lý tiện nghi',
            },
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tentinh', models.CharField(max_length=200, null=True)),
                ('anhtinh', models.ImageField(blank=True, null=True, upload_to='tinh/%Y/%m')),
            ],
            options={
                'verbose_name_plural': 'Quản lý tỉnh thành',
            },
        ),
        migrations.CreateModel(
            name='Xa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tenXa', models.CharField(max_length=200, null=True)),
                ('huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.huyen')),
            ],
            options={
                'verbose_name_plural': 'Quản lý xã phường',
            },
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tenphong', models.CharField(max_length=200, null=True)),
                ('dientich', models.CharField(max_length=200, null=True)),
                ('phongtam', models.CharField(max_length=200, null=True)),
                ('soluongnguoi', models.IntegerField()),
                ('giaphong', models.FloatField()),
                ('soluong', models.IntegerField()),
                ('khachsan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachsan')),
                ('tiennghi', models.ManyToManyField(blank=True, to='app.tiennghi')),
            ],
            options={
                'verbose_name_plural': 'Quản lý phòng',
            },
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tenkhuyenmai', models.CharField(max_length=200, null=True)),
                ('thoigian_bd', models.DateTimeField()),
                ('thoigian_kt', models.DateTimeField()),
                ('giatri_km', models.FloatField()),
                ('phong', models.ManyToManyField(blank=True, to='app.phong')),
            ],
            options={
                'verbose_name_plural': 'Quản lý khuyến mãi',
            },
        ),
        migrations.AddField(
            model_name='khachsan',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tinh'),
        ),
        migrations.AddField(
            model_name='khachsan',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.xa'),
        ),
        migrations.AddField(
            model_name='huyen',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tinh'),
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank'), ('on_arrival', 'On Arrival')], default='on_arrival', max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('trangthai', models.CharField(choices=[('CTT', 'Chưa thanh toán'), ('DNP', 'Đã nhận phòng'), ('DH', 'Đã hủy')], default='CTT', max_length=3)),
                ('thanh_toan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.payment_vnpay')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quản lý hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='Danhgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('diem', models.IntegerField()),
                ('binhluan', models.CharField(max_length=200, null=True)),
                ('hoadon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hoadon')),
            ],
            options={
                'verbose_name_plural': 'Quản lý đánh giá',
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ngay_gio_nhan', models.DateTimeField()),
                ('ngay_gio_tra', models.DateTimeField()),
                ('soluong_phong', models.IntegerField()),
                ('soluong_dem', models.IntegerField()),
                ('dongia', models.FloatField()),
                ('hoadon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hoadon')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
            options={
                'verbose_name_plural': 'Quản lý chi tiết hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='AnhPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('anhphong', models.ImageField(blank=True, null=True, upload_to='anhphong/%Y/%m')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
            options={
                'verbose_name_plural': 'Quản lý ảnh phòng',
            },
        ),
        migrations.CreateModel(
            name='AnhKhachSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('anhks', models.ImageField(blank=True, null=True, upload_to='anhks/%Y/%m')),
                ('khachsan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.khachsan')),
            ],
            options={
                'verbose_name_plural': 'Quản lý ảnh khách sạn',
            },
        ),
    ]
