# Generated by Django 4.2.6 on 2024-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitiethoadon',
            name='tongtien',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
