# Generated by Django 4.2.6 on 2024-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anhkhachsan',
            name='anhks',
            field=models.ImageField(blank=True, null=True, upload_to='anhks/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='anhphong',
            name='anhphong',
            field=models.ImageField(blank=True, null=True, upload_to='anhphong/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tiennghi',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tinh',
            name='anhtinh',
            field=models.ImageField(blank=True, null=True, upload_to='tinh/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m'),
        ),
    ]
