# Generated by Django 4.2.6 on 2024-06-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_anhkhachsan_anhks_alter_anhphong_anhphong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachsan',
            name='tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tinh'),
        ),
    ]
