# Generated by Django 5.0.6 on 2024-06-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_khachsan_tinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachsan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiennghi',
            name='khachsan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.khachsan'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('provider', 'Provider'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
