# Generated by Django 5.0.6 on 2024-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_khachsan_owner_tiennghi_khachsan_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
