# Generated by Django 4.2.6 on 2024-06-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_payment_vnpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiennghi',
            name='khachsan',
        ),
    ]
