# Generated by Django 5.0.6 on 2024-06-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_hoadon_trangthai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiennghi',
            name='loai_tiennghi',
        ),
        migrations.AlterModelOptions(
            name='anhkhachsan',
            options={'verbose_name_plural': 'Quản lý ảnh khách sạn'},
        ),
        migrations.AlterModelOptions(
            name='anhphong',
            options={'verbose_name_plural': 'Quản lý ảnh phòng'},
        ),
        migrations.AlterModelOptions(
            name='chitiethoadon',
            options={'verbose_name_plural': 'Quản lý chi tiết hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='danhgia',
            options={'verbose_name_plural': 'Quản lý đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='dichvu',
            options={'verbose_name_plural': 'Quản lý dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='hoadon',
            options={'verbose_name_plural': 'Quản lý hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='huyen',
            options={'verbose_name_plural': 'Quản lý quận huyện'},
        ),
        migrations.AlterModelOptions(
            name='khachsan',
            options={'verbose_name_plural': 'Quản lý khách sạn'},
        ),
        migrations.AlterModelOptions(
            name='khuyenmai',
            options={'verbose_name_plural': 'Quản lý khuyến mãi'},
        ),
        migrations.AlterModelOptions(
            name='phong',
            options={'verbose_name_plural': 'Quản lý phòng'},
        ),
        migrations.AlterModelOptions(
            name='tiennghi',
            options={'verbose_name_plural': 'Quản lý tiện nghi'},
        ),
        migrations.AlterModelOptions(
            name='tinh',
            options={'verbose_name_plural': 'Quản lý tỉnh thành'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Quản lý người dùng'},
        ),
        migrations.AlterModelOptions(
            name='xa',
            options={'verbose_name_plural': 'Quản lý xã phường'},
        ),
        migrations.RemoveField(
            model_name='tiennghi',
            name='khachsan',
        ),
        migrations.DeleteModel(
            name='LoaiTienNghi',
        ),
    ]
