# Generated by Django 4.2.6 on 2024-06-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_tiennghi_khachsan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiennghi',
            name='loai_tiennghi',
        ),
        migrations.DeleteModel(
            name='LoaiTienNghi',
        ),
    ]
